### ISSUE TITLE
Jest tests are not running in CircleCI

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/data-catalog-components#69]
Jest tests are not running in CircleCI

**Comment by dasumner** [comment]
I think this was spawned from a discussion with @fmizzell .  Checking with him for additional details.

**Comment by dasumner** [comment]
> yes, if you look at a build from that repo in Circle you will see the tests running. I believe it happens during npm install or something odd like that. I believe you can also see that some tests are failing, but the build will still act as if nothing is wrong.

**Comment by dgading** [comment]
There was an issue where Jest wouldn't run in the container Circle CI was using based on some dependency. So I moved them to the cypress test section, but then when they failed there it didn't exit the code. I'll see if I can get it back into it's own run section of Circle CI.

**Comment by dgading** [comment]
This seems to be fixed now. When DKTL commands were updated, found a way to set the correct version of node in the app. See #87
