### ISSUE TITLE
Data table adjustments

### ISSUE THREAD

**Issue by janette** [GetDKAN/data-catalog-components#81]
I know we are waiting for UX team results but just jotting down some thoughts

- [x] Show 'no result found' message rather than lose access to the table.
- [ ] option for horizontal scroll at the top
- [x] keep row data from wrapping by adding `...` when it overruns the column width
- [ ] option to freeze header row
- [ ] restore the 'view in full screen modal' button
- [x] zebra striping does not carry through when scrolling to the right

**Comment by dgading** [comment]
Filter to 0 should not remove the entire table.

**Comment by kimwdavidson** [comment]
@dgading to separate into smaller bites

**Comment by dgading** [comment]
To keep changes moving, I've addressed to priority issues that were breaking the data tables and moved the rest into their own tickets, see:
- https://github.com/GetDKAN/data-catalog-components/issues/115
- https://github.com/GetDKAN/data-catalog-components/issues/116
- https://github.com/GetDKAN/data-catalog-components/issues/117
